### ISSUE TITLE
Handle undefined references

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/userguide#2]
When building the user guide, there are warning about a number of undefined references (all to section labels). These are probably references to obsolete plugins or other stuff that has been removed or moved around. We should remove those references.

**Comment by adam-funk** [comment]
I removed them in the past week as part of another tidy-up. But I can't figure out this one:

    LaTeX Warning: Reference `sec:eval:qawarning' on page 455 undefined on input li

because it is defined in a subsection command with exactly the same spelling:

    $ grep sec:eval:qawarning *.tex
    evaluation.tex:Section~\ref{sec:eval:qawarning} for more detail and advice on preventing
    evaluation.tex:\subsection[sec:eval:qawarning]{A warning about feature values}

**Comment by ianroberts** [comment]
@adam-funk that `\subsection` should be `\subsect` - our custom command that takes a label and puts in the `[#]` permalink

**Comment by adam-funk** [comment]
Oops, I introduced that bug recently, but I've just pushed the correction.

Should all the `\subsection` commands be changed to `\subsect`?

**Comment by ianroberts** [comment]
Only the ones that have a `[label]` - without the label bit `\subsect{foo}` is just an alias for `\subsection{foo}`

**Comment by adam-funk** [comment]
OK, I've done some grep-checks and all the ones with labels are now `\subsect`.
