### ISSUE TITLE
add links to GATE Cloud hosted services where appropriate

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/userguide#4]
i.e. when mentioning ANNIE link to the REST API endpoint at https://cloud-api.gate.ac.uk/process-document/annie-named-entity-recognizer -- if opened in a browser this will redirect to the shop page (https://cloud.gate.ac.uk/shopfront/displayItem/annie-named-entity-recognizer) with a message about using a REST client.

**Comment by muneerahp** [comment]
Done here: #5 , mention if you think wording could change anywhere.
